### ISSUE TITLE
Cross-compile for Scala.js (using JS's JSON instead of Jackson)

### ISSUE THREAD

**Issue by rpiaggio** [playframework/play-json#29] opened 2017-01-25 21:25 UTC

**Comment by cchantep** [comment] 2017-01-25 22:00
Duplicate of #13 

> Please first check the existing ticket.

**Closed by cchantep** 2017-01-25 22:00 UTC

**Comment by rpiaggio** [comment] 2017-01-25 22:48
@cchantep This is great.

Sorry, I checked existing issues, but not PRs. I usually create an issue before starting to work on something so that I can cross-reference it from commit messages, but I understand that no everyone works this way.

I will fork from your repo and give it a try.
