### ISSUE TITLE
Why there is need for `val vjs = ...` in JsMacroImpl:503?

### ISSUE THREAD

**Issue by mr-git** [playframework/play-json#101] opened 2017-09-04 17:23 UTC
During compilation for 2.12 with set of scalac options:
```    
    "-encoding", "utf8",
    "-feature",
    "-deprecation",
    "-unchecked",
    "-deprecation",
    "-target:jvm-1.8",
    "-language:_",
    "-Xlog-reflective-calls",
    "-Xlint",
    "-Ywarn-adapted-args",
    "-Ywarn-numeric-widen",
    "-Xfatal-warnings",
    "-Xfuture"
```

I got error like: 

```
....local val vjs in value $anonfun is never used
[error]   implicit val XXXFormat: Format[XXX] = Json.format[XXX]
```
And I couldn't find the source of the error, till I searched in `All Places` in IDEA...
https://github.com/playframework/play-json/blob/2.6.3/play-json/shared/src/main/scala/JsMacroImpl.scala#L503

It would be nice, if code generated by macros would be clean and minimal. :)

**Comment by gmethvin** [comment] 2017-09-07 00:52
It looks like it was probably not actually needed. I agree we should keep the macros minimal. Are you interested in contributing a fix?

**Comment by cchantep** [comment] 2017-09-07 07:26
For me this generated `ValDef` is not always unused, so "simply" removing will break the macros.

**Comment by cchantep** [comment] 2017-09-07 09:58
For me that's rather related to https://github.com/playframework/play-json/pull/102

**Comment by mr-git** [comment] 2017-09-07 18:21
how exactly it can get used?

**Comment by cchantep** [comment] 2017-09-07 22:27
I would "reverse" the question: how it could not be used. I guess you're using seal trait with no subclass.

**Comment by mr-git** [comment] 2017-09-08 11:22
hm..
```
             case Some(tjs) => {
               val vjs = obj.value.get("_value").getOrElse(obj)
               tjs.validate[String].flatMap { dis => $cases }
             }
```
I do not see, how it is useful in this context, unless `obj.value.get()` has some interesting and needed side-effect (I didn't check, but I trust scalac that `vjs` is not used there)

**Comment by cchantep** [comment] 2017-09-08 15:30
Because this generated code is not alone, and `vjs` is used in `$cases`

**Comment by mr-git** [comment] 2017-09-08 18:21
Ok, stupid question: why init `vjs` if it is not needed in half of cases? Would this work if on https://github.com/playframework/play-json/blob/2.6.3/play-json/shared/src/main/scala/JsMacroImpl.scala#L495 we would write?:
```
cq"${typeNaming(t)} => $reader.reads(obj.value.get("_value").getOrElse(obj))" :: out
```

**Comment by cchantep** [comment] 2017-09-08 18:34
It's not "needed in half cases", it's used for all cases in `$cases` except the `case _` for error handling. The unused warning indicated that there is no other case than this one, which can only occurs if the sealed family has no know subclass (in which situation, such sealed family doesn't make sense).

`cq"""${typeNaming(t)} => $reader.reads(obj.value.get("_value").getOrElse(obj))""" :: out` but doesn't fix the root cause, which is that in case of an empty sealed family, a compilation error must be raised as that's an invalid usage of the macro.

**Comment by mr-git** [comment] 2017-09-08 19:00
ok, this is my code
```
sealed trait H {
  def code: String
}

object H {
  case object D extends H {
    def code: String = "D"
  }

  case object T extends H {
    def code: String = "T"
  }

  implicit val HFormat: Format[H] = Json.format[H]
}
```
Error message:
```
[error] /<path>/H.scala:7:48: local val vjs in value $anonfun is never used
[error]   implicit val HFormat: Format[H] = Json.format[H]
[error]                                                ^
[error] one error found
```

**Comment by cchantep** [comment] 2017-09-08 19:33
It doesn't work because the subclasses and the macro call are in the same compilation scope, which is not yet full defined/ended, and so types defined in the scope are not made available by the compiler for macro in same scope.

**Comment by mr-git** [comment] 2017-09-08 20:11
Then...is it scalac issue?

**Comment by cchantep** [comment] 2017-09-08 20:28
A [known limitation](https://issues.scala-lang.org/browse/SI-7046) (that could be documented along the macro usage). That could be fixed with Scala 2.12, but macros are using a cross version workaround fixing other issues.

**Comment by mr-git** [comment] 2017-09-09 18:46
so, if this is known feature of scalac... why `cq"""${typeNaming(t)} => $reader.reads(obj.value.get("_value").getOrElse(obj))""" :: out` would not work better? Would it create performance hit due to several/many such places generated?

**Comment by cchantep** [comment] 2017-09-10 10:12
It would fix the unused warning, but not the root cause, which is to prevent the compilation in case the subclasses are not known.

With the compilation check, there is no need to move such code, it can be kept as it will never be generated for an empty sealed family.

**Comment by mr-git** [comment] 2017-09-10 16:48
I wonder, how likely it will get fixed in Scala 2.12.4 and if that will be soon or Blizzard's soon™ :)
For me it seems that making fix in Play-JSON could happen much faster and way sooner than Scala fix.
What you think? Shall I move the code and make PR?

**Comment by cchantep** [comment] 2017-09-10 17:21
Fixing Scala compiler issue is out of the Play scope. The workaround is doing its best. For me the only thing actionable is the specified PR https://github.com/playframework/play-json/pull/102

**Comment by mr-git** [comment] 2017-09-11 07:09
Now I am lost - does #102 cover this issue too? If yes, when 2.6.4 will get released?

**Comment by cchantep** [comment] 2017-09-11 10:40
The PR prevent compilation when subclasses aren't found, so a workaround. You can rather use the MailingList to ask question (release date).

**Closed** 2017-09-13 10:30 UTC
